language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: linux
      compiler: gcc
      env: HOST=i386-pc-linux-gnu
  include:
    - os: linux
      compiler: i686-w64-mingw32-gcc
      env: HOST=i686-w64-mingw32

install:
  - ./.travis/install.sh

script:
  - ./autogen.sh
  - if test x"$HOST" = x"i386-pc-linux-gnu"; then CC="$CC -m32"; CXX="$CXX -m32"; fi
  - ./configure ${HOST+--host=$HOST}
  - make
  - make dist
  - make check
  - cat */testsuite/libffi.log
